---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[lamp-stack::default]
      - recipe[lamp-stack::database]
      - recipe[lamp-stack::web]
    attributes:
